# Generated by Django 5.1 on 2024-12-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='robot',
            index=models.Index(fields=['serial'], name='robots_robo_serial_0ec49a_idx'),
        ),
        migrations.AddIndex(
            model_name='robot',
            index=models.Index(fields=['created'], name='robots_robo_created_21a443_idx'),
        ),
    ]
